/*
 * @Author: shen
 * @Date: 2022-06-09 10:13:01
 * @LastEditors: shen
 * @LastEditTime: 2025-07-27 11:23:34
 * @Description:
 */
import { ProFieldType } from './fieldType'
import FieldText from './fields/FieldText'
import FieldDigit from './fields/FieldDigit'
import FieldDigitRange from './fields/FieldDigitRange'
import FieldTextarea from './fields/FieldTextarea'
import FieldPassword from './fields/FieldPassword'
import FieldSelect from './fields/FieldSelect'
import FieldTreeSelect from './fields/FieldTreeSelect'
import FieldCheckbox from './fields/FieldCheckbox'
import FieldCheckboxGroup from './fields/FieldCheckboxGroup'
import FieldRadioGroup from './fields/FieldRadioGroup'
import FieldCascader from './fields/FieldCascader'
import FieldSwitch from './fields/FieldSwitch'
import FieldSlider from './fields/FieldSlider'
import FieldRate from './fields/FieldRate'
import FieldDatePicker from './fields/FieldDatePicker'
import FieldDateRangePicker from './fields/FieldDateRangePicker'
import FieldTimePicker from './fields/FieldTimePicker'
import FieldTimeRangePicker from './fields/FieldTimeRangePicker'
import FieldUploadButton from './fields/FieldUploadButton'
import FieldUploadDragger from './fields/FieldUploadDragger'
import FieldUploadPicture from './fields/FieldUploadPicture'
import FieldUploadPictureList from './fields/FieldUploadPictureList'
// import FieldEditor from './fields/FieldEditor'

export const fieldComponentMap: Partial<Record<`${ProFieldType}`, any>> = {
  text: FieldText,
  digit: FieldDigit,
  digitRange: FieldDigitRange,
  select: FieldSelect,
  cascader: FieldCascader,
  textarea: FieldTextarea,
  password: FieldPassword,
  treeSelect: FieldTreeSelect,
  checkbox: FieldCheckbox,
  checkboxGroup: FieldCheckboxGroup,
  radioGroup: FieldRadioGroup,
  switch: FieldSwitch,
  slider: FieldSlider,
  rate: FieldRate,
  date: FieldDatePicker,
  dateRange: FieldDateRangePicker,
  time: FieldTimePicker,
  timeRange: FieldTimeRangePicker,
  uploadButton: FieldUploadButton,
  uploadDragger: FieldUploadDragger,
  uploadPicture: FieldUploadPicture,
  uploadPictureList: FieldUploadPictureList,
  // editor: FieldEditor
}

export const fieldWidthSizeMap = {
  // 适用于短数字，短文本或者选项
  xs: 104,
  s: 216,
  // 适用于较短字段录入、如姓名、电话、ID 等。
  sm: 216,
  m: 328,
  // 标准宽度，适用于大部分字段长度。
  md: 328,
  l: 440,
  // 适用于较长字段录入，如长网址、标签组、文件路径等。
  lg: 440,
  // 适用于长文本录入，如长链接、描述、备注等，通常搭配自适应多行输入框或定高文本域使用。
  xl: 552,
}

export const fieldPropsMap: Partial<Record<`${ProFieldType}`, string[]>> = {
  text: [
    'type',
    'disabled',
    'addonAfter',
    'addonBefore',
    'allowClear',
    'bordered',
    'clearIcon',
    'defaultValue',
    'id',
    'prefix',
    'showCount',
    'maxlength',
    'status',
    'size',
    'suffix',
    'placeholder',
    'autocomplete',
    'onPressEnter',
    'onFocus',
    'onBlur',
    'onInput',
    'onClear',
  ],
  digit: [
    'disabled',
    'addonAfter',
    'addonBefore',
    'bordered',
    'clearIcon',
    'controls',
    'decimalSeparator',
    'formatter',
    'keyboard',
    'max',
    'min',
    'parser',
    'precision',
    'step',
    'stringMode',
    'upIcon',
    'downIcon',
    'defaultValue',
    'id',
    'prefix',
    'status',
    'placeholder',
    'onPressEnter',
    'onStep',
    'onFocus',
    'onBlur',
    'onInput',
    'onClear',
  ],
  digitRange: [
    'separatorWidth',
    'separator',
    'disabled',
    'addonAfter',
    'addonBefore',
    'bordered',
    'clearIcon',
    'controls',
    'decimalSeparator',
    'formatter',
    'keyboard',
    'max',
    'min',
    'parser',
    'precision',
    'step',
    'stringMode',
    'upIcon',
    'downIcon',
    'defaultValue',
    'id',
    'prefix',
    'status',
    'placeholder',
    'onPressEnter',
    'onStep',
    'onFocus',
    'onBlur',
    'onInput',
    'onClear',
  ],
  select: [
    'id',
    'pagination',
    'placeholder',
    'disabled',
    'allowClear',
    'autoClearSearchValue',
    'autofocus',
    'bordered',
    'clearIcon',
    'defaultActiveFirstOption',
    'defaultOpen',
    'popupClassName',
    'dropdownMatchSelectWidth',
    'dropdownMenuStyle',
    'dropdownRender',
    'dropdownStyle',
    'fieldNames',
    'filterOption',
    'filterSort',
    'firstActiveValue',
    'getPopupContainer',
    'labelInValue',
    'listHeight',
    'maxTagCount',
    'maxTagPlaceholder',
    'maxTagTextLength',
    'menuItemSelectedIcon',
    'mode',
    'notFoundContent',
    'open',
    'option',
    'optionFilterProp',
    'optionLabelProp',
    'options',
    'placement',
    'removeIcon',
    'searchValue',
    'showArrow',
    'showSearch',
    'size',
    'status',
    'suffixIcon',
    'tagRender',
    'tokenSeparators',
    'virtual',
    'onBlur',
    'onFocus',
    'onDeselect',
    'onDropdownVisibleChange',
    'onInputKeyDown',
    'onMouseenter',
    'onMouseleave',
    'onPopupScroll',
    'onSearch',
    'onSelect',
  ],
  textarea: [
    'id',
    'disabled',
    'allowClear',
    'autoSize',
    'defaultValue',
    'showCount',
    'maxlength',
    'placeholder',
    'onPressEnter',
    'onFocus',
    'onBlur',
    'onInput',
    'onClear',
  ],
  password: [
    'id',
    'disabled',
    'addonAfter',
    'addonBefore',
    'allowClear',
    'bordered',
    'clearIcon',
    'defaultValue',
    'id',
    'visibilityToggle',
    'prefix',
    'showCount',
    'maxlength',
    'status',
    'size',
    'suffix',
    'placeholder',
    'autocomplete',
    'onPressEnter',
    'onFocus',
    'onBlur',
    'onInput',
    'onClear',
  ],
  treeSelect: [
    'id',
    'multiple',
    'options',
    'showCheckedStrategy',
    'searchPlaceholder',
    'replaceFields',
    'loadData',
    'filterTreeNode',
    'placeholder',
    'disabled',
    'allowClear',
    'popupClassName',
    'defaultValue',
    'dropdownMatchSelectWidth',
    'dropdownStyle',
    'fieldNames',
    'getPopupContainer',
    'labelInValue',
    'listHeight',
    'maxTagCount',
    'maxTagPlaceholder',
    'notFoundContent',
    'placement',
    'searchValue',
    'showSearch',
    'size',
    'status',
    'suffixIcon',
    'tagRender',
    'title',
    'treeCheckable',
    'treeCheckStrictly',
    'treeData',
    'treeDataSimpleMode',
    'treeDefaultExpandAll',
    'treeDefaultExpandedKeys',
    'treeExpandedKeys',
    'treeIcon',
    'treeLine',
    'treeLoadedKeys',
    'treeNodeFilterProp',
    'treeNodeLabelProp',
    'onDropdownVisibleChange',
    'onSearch',
    'onSelect',
    'onTreeExpand',
    'onUpdate:treeExpandedKeys',
    'onUpdate:searchValue',
  ],
  checkbox: ['id', 'autofocus', 'disabled', 'indeterminate'],
  checkboxGroup: ['id', 'disabled', 'name', 'options'],
  radioGroup: [
    'id',
    'class',
    'disabled',
    'name',
    'options',
    'optionType',
    'buttonStyle',
    'radioLabel',
  ],
  cascader: [
    'id',
    'disabled',
    'name',
    'options',
    'placeholder',
    'allowClear',
    'autofocus',
    'bordered',
    'clearIcon',
    'changeOnSelect',
    'defaultValue',

    'displayRender',
    'popupClassName',
    'dropdownStyle',
    'expandTrigger',
    'fieldNames',
    'getPopupContainer',
    'loadData',
    'maxTagCount',
    'maxTagPlaceholder',
    'multiple',
    'notFoundContent',
    'open',
    'placement',
    'showCheckedStrategy',
    'removeIcon',
    'searchValue',
    'showSearch',
    'status',
    'suffixIcon',
    'tagRender',
    'onDropdownVisibleChange',
    'onSearch',
  ],
  switch: [
    'id',
    'checkedChildren',
    'size',
    'checkedValue',
    'disabled',
    'loading',
    'unCheckedChildren',
    'unCheckedValue',
    'onClick',
  ],
  slider: [
    'id',
    'disabled',
    'dots',
    'included',
    'mark',
    'marks',
    'max',
    'min',
    'range',
    'reverse',
    'step',
    'vertical',
    'tipFormatter',
    'tooltipPlacement',
    'tooltipOpen',
    'getTooltipPopupContainer',
    'onAfterChange',
  ],
  rate: [
    'id',
    'allowClear',
    'allowHalf',
    'character',
    'count',
    'disabled',
    'tooltips',
    'onBlur',
    'onFocus',
    'onHoverChange',
    'onKeydown',
  ],
  date: [
    'id',
    'allowClear',
    'bordered',
    'dateRender',
    'disabled',
    'disabledDate',
    'format',
    'dropdownClassName',
    'getPopupContainer',
    'inputReadOnly',
    'locale',
    'mode',
    'nextIcon',
    'open',
    'picker',
    'placeholder',
    'placement',
    'popupStyle',
    'prevIcon',
    'presets',
    'status',
    'suffixIcon',
    'superNextIcon',
    'superPrevIcon',
    'valueFormat',
    'defaultPickerValue',
    'disabledTime',
    'renderExtraFooter',
    'showNow',
    'showTime',
    'showToday',
    'monthCellRender',
    'onOpenChange',
    'onPanelChange',
    'onOk',
  ],
  dateRange: [
    'allowClear',
    'bordered',
    'dateRender',
    'disabled',
    'disabledDate',
    'format',
    'dropdownClassName',
    'getPopupContainer',
    'inputReadOnly',
    'locale',
    'mode',
    'nextIcon',
    'open',
    'picker',
    'placeholder',
    'placement',
    'popupStyle',
    'prevIcon',
    'presets',
    'status',
    'suffixIcon',
    'superNextIcon',
    'superPrevIcon',
    'valueFormat',
    'id',
    'allowEmpty',
    'defaultPickerValue',
    'disabledTime',
    'presets',
    'showTime',
    'ranges',
    'renderExtraFooter',
    'separator',
    'onOpenChange',
    'onPanelChange',
    'onCalendarChange',
    'onOk',
  ],
  time: [
    'id',
    'allowClear',
    'bordered',
    'clearIcon',
    'clearText',
    'disabled',
    'disabledTime',
    'format',
    'getPopupContainer',
    'hideDisabledOptions',
    'hourStep',
    'inputReadOnly',
    'minuteStep',
    'open',
    'placeholder',
    'placement',
    'popupClassName',
    'popupStyle',
    'renderExtraFooter',
    'secondStep',
    'showNow',
    'status',
    'suffixIcon',
    'use12Hours',
    'valueFormat',
    'onOpenChange',
  ],
  timeRange: [
    'allowClear',
    'bordered',
    'dateRender',
    'disabled',
    'disabledDate',
    'format',
    'dropdownClassName',
    'getPopupContainer',
    'inputReadOnly',
    'locale',
    'mode',
    'nextIcon',
    'open',
    'picker',
    'placeholder',
    'placement',
    'popupStyle',
    'prevIcon',
    'presets',
    'status',
    'suffixIcon',
    'superNextIcon',
    'superPrevIcon',
    'valueFormat',
    'id',
    'allowEmpty',
    'defaultPickerValue',
    'disabledTime',
    'presets',
    'ranges',
    'renderExtraFooter',
    'separator',
    'order',
    'onOpenChange',
    'onPanelChange',
    'onCalendarChange',
    'onOk',
  ],
  uploadButton: [
    'disabled',
    'id',
    'accept',
    'action',
    'beforeUpload',
    'customRequest',
    'data',
    'directory',
    'disabled',
    'downloadIcon',
    'fileList',
    'headers',
    'iconRender',
    'isImageUrl',
    'itemRender',
    'listType',
    'maxCount',
    'method',
    'multiple',
    'name',
    'openFileDialogOnClick',
    'previewFile',
    'previewIcon',
    'progress',
    'removeIcon',
    'showUploadList',
    'supportServerRender',
    'withCredentials',
    'onDownload',
    'onDrop',
    'onPreview',
    'onReject',
    'onRemove',
    'title',
    'max',
    'buttonProps',
  ],
  uploadDragger: [
    'disabled',
    'id',
    'accept',
    'action',
    'beforeUpload',
    'customRequest',
    'data',
    'directory',
    'disabled',
    'downloadIcon',
    'fileList',
    'headers',
    'iconRender',
    'isImageUrl',
    'itemRender',
    'listType',
    'maxCount',
    'method',
    'multiple',
    'name',
    'openFileDialogOnClick',
    'previewFile',
    'previewIcon',
    'progress',
    'removeIcon',
    'showUploadList',
    'supportServerRender',
    'withCredentials',
    'onDownload',
    'onDrop',
    'onPreview',
    'onReject',
    'onRemove',
    'title',
    'description',
    'max',
    'buttonProps',
  ],
  uploadPicture: [
    'disabled',
    'id',
    'customRequest',
    'accept',
    'action',
    'beforeUpload',
    'name',
    'headers',
    'isCropper',
    'cropperModalTitle',
    'cropperModalWidth',
    'cropperWidth',
    'cropperHeight',
    'cropperProps',
    'width',
    'height',
    'title',
    'data',
    'showTitle',
    'allowClear',
  ],
  uploadPictureList: [
    'disabled',
    'id',
    'data',
    'headers',
    'customRequest',
    'accept',
    'action',
    'multiple',
    'maxCount',
    'beforeUpload',
    'name',
    'previewFile',
    'allowClear',
    'width',
    'height',
    'crossOrigin',
  ],
  editor: [
    'autofocus',
    'indentWithTab',
    'tabSize',
    'theme',
    'autoDestroy',
    'phrases',
    'root',
    'extensions',
    'selection',
    'height',
    'disabled',
    'placeholder',
    'onFocus',
    'onBlur',
    'onReady',
    'onUpdate',
  ],
}

export const fieldDateFormatterMap: Record<string, string> = {
  date: 'YYYY-MM-DD',
  year: 'YYYY',
  month: 'YYYY-MM',
  week: 'YYYY-wo',
  quarter: 'YYYY-QQ',
  time: 'HH:mm:ss',
}
