packages:
  - packages/*
  - docs
  - play
  - internal/*

catalog:
  '@ant-design/colors': ^7.2.1
  '@ant-design/icons-vue': ^7.0.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@microsoft/api-extractor': ^7.52.11
  '@pnpm/find-workspace-packages': ^4.0.16
  '@pnpm/logger': ^4.0.0
  '@pnpm/types': ^8.4.0
  '@rollup/plugin-commonjs': ^28.0.6
  '@rollup/plugin-node-resolve': ^16.0.1
  '@rollup/plugin-replace': ^6.0.2
  '@stylistic/stylelint-plugin': ^3.1.2
  '@tsconfig/node22': ^22.0.2
  '@types/gulp': ^4.0.9
  '@types/gulp-autoprefixer': ^0.0.33
  '@types/gulp-less': ^0.0.36
  '@types/gulp-rename': ^2.0.6
  '@types/jsdom': ^21.1.7
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.3.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vue/eslint-config-prettier': ^10.2.0
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^13.8.0
  ant-design-vue: ^4.2.0
  autoprefixer: ^10.4.21
  chalk: ^5.6.0
  commitlint-plugin-function-rules: ^4.0.2
  components-helper: ^2.2.0
  concurrently: ^9.2.1
  consola: ^3.4.2
  cropperjs: ^1.6.1
  cspell: ^9.0.1
  cssnano: ^7.1.1
  csstype: ^2.6.20
  cz-git: ^1.11.1
  czg: ^1.11.1
  dayjs: ^1.11.15
  esbuild: ^0.25.9
  eslint: ^9.31.0
  eslint-plugin-vue: ~10.3.0
  fast-glob: ^3.3.3
  fs-extra: ^11.3.1
  gulp: ^4.0.2
  gulp-autoprefixer: ^9.0.0
  gulp-less: ^5.0.0
  gulp-rename: ^2.1.0
  jiti: ^2.4.2
  jsdom: ^26.1.0
  lefthook: ^1.12.3
  less: ^4.4.1
  lodash: ^4.17.21
  lodash-es: ^4.17.21
  lodash-unified: ^1.0.3
  npm-run-all2: ^8.0.4
  pkg-types: ^2.3.0
  postcss: ^8.5.6
  postcss-html: ^1.8.0
  postcss-less: ^6.0.0
  prettier: ^3.6.2
  resize-observer-polyfill: ^1.5.1
  rimraf: ^6.0.1
  rollup: ^4.49.0
  rollup-plugin-esbuild: ^6.2.1
  stylelint: ^16.19.1
  stylelint-config-recess-order: ^6.0.0
  stylelint-config-recommended: ^16.0.0
  stylelint-config-recommended-vue: ^1.6.0
  stylelint-config-standard: ^38.0.0
  stylelint-order: ^7.0.0
  stylelint-prettier: ^5.0.3
  tsx: ^4.19.3
  typescript: ~5.8.0
  unbuild: ^2.0.0
  vite: ^7.0.6
  vite-plugin-vue-devtools: ^8.0.0
  vitepress: 2.0.0-alpha.12
  vue: 3.5.20
  vue-router: ^4.5.1
  vue-tsc: ^2.0.28
  vue-types: ^6.0.0
  '@vue/shared': ^3.5.20
  scroll-into-view-if-needed: ^3.1.0
  unplugin-vue-macros: ^2.7.11
